### ISSUE TITLE
Warn if curves have minimal overlap in integration interval

### ISSUE THREAD

**Issue by YodaEmbedding** [FAU-LMS/bjontegaard#3]
For instance, computing BD-PSNR between the "input compression" (reference) curve and the other curves in the following diagram gives really weird values:

![](https://github.com/FAU-LMS/bjontegaard/assets/721196/d6bf995d-bff6-4b6f-b18d-730bf130f156)

...Perhaps users should be warned if the overlapping interval of the non-reference curve is much smaller than the inputted interval.

Something like (but not necessarily exactly):

```python
REQUIRED_INTERVAL_OVERLAP = 0.8

if (x_max - x_min) < REQUIRED_INTERVAL_OVERLAP * (xB.max() - xB.min()):
    warnings.warn("Insufficient overlap.")
```

...actually, better would be to check the derivatives so that uninformative "flat" regions (i.e. dy/dx=0) can be ignored in the required amount of overlapping regions.

----

Or even better: *conservatively* "extrapolate" via horizontal lines so that there is sufficient overlap within the integration interval:

![bd_psnr_example_2](https://github.com/FAU-LMS/bjontegaard/assets/721196/504940ec-8c31-49ac-b2a1-42e03cb26cf1)

Simplified example implementation:

```python
EPSILON = 1e-12

x_max = max(x_ref[-1], x_curr[-1])

if xA[-1] < x_max:
    xA = np.array([*xA, x_max])
    yA = np.array([*yA, yA[-1] + EPSILON])

if xB[-1] < x_max:
    xB = np.array([*xB, x_max])
    yB = np.array([*yB, yB[-1] + EPSILON])
```

...Though arguably, even this method has its issues, e.g. unfairly penalizing curves that haven't yet reached their "flattening" points. Nonetheless, it should help give more realistic values in many cases that the current method does not, without making "normal" cases worse. We could raise an error in cases where the derivative (of a linearly interpolated spline?) is not sufficiently flat near the boundary. And it's also a good idea to notify the user via warning when choosing to extrapolate.

This requires some care to implement safely, though. Automated tests should help avoid breaking "normal" cases, while showing clear improvements for "degenerate" cases (as pictured above).

I can submit a PR for the horizontal extrapolation, if desired.

---

<sup>To further "improve" this method, we could even add an option for extrapolating via a log curve fit, which would improve cases where the user did not fully measure the codec. And maybe some error bars and/or range of values. And raise an error when the space of reasonable extrapolations has too much variance.</sup>

**Comment by labradon** [comment]
Thank you for your time and effort. The warning for insufficient overlap intervals is now implemented and configurable as `min_overlap`. The default value is 0.75, a value of 0 would silence all warnings. This is part of version `1.3.0`.

Regarding the extrapolation of values for bd calculation, I discussed with some colleagues. Although we agree that it might be useful to do this in certain situations, it is not generalizable and provides unreliable results in many cases. As `bjontegaard` should provide the general means for BD metric calculations, these extrapolations would be the responsibility of the user. If desired, the user could extrapolate their data explicitly before inserting the values into the provided functions for BD metric calculation. The newly added `bd_linear` API should be helpful here to cover a wide range of use cases.

You mention: *Or even better: conservatively "extrapolate" via horizontal lines so that there is sufficient overlap within the integration interval*.
In this case, the question arises what we define as integration interval. Theoretically, the horizontal line extrapolation could go on to infinity. This would mean that the BD would simply be the difference between the two horizontal lines. If desired, this value can be calculated from the two *highest* metric values alone.
